### ISSUE TITLE
question about timer choice

### ISSUE THREAD

**Issue by cstout1** [SKeenan07/mac-admin-scripts#1]
Was there a technical reason such as a limitation that caused you to choose 970 seconds as the maximum idle time? It seems very specific and I don't see an obvious reason that would prevent a greater duration. Just curious. Thanks for sharing this fantastic script.

**Comment by SKeenan07** [comment]
@cstout1 We used another solution to automatically restart/log out idle lab machines that stopped working. The specified time in that solution was 970 seconds, so I just rolled that over into this script. I tested the script with various idle times during development (mainly because I was too impatient to wait the full 970 seconds every time), and it worked fine.
